FROM node:24-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173

# The --host flag is strictly required for Vite to be accessible outside the Docker container
CMD ["npm", "run", "dev", "--", "--host"]